### ISSUE TITLE
Help Us!

### ISSUE THREAD

**Issue by edenxu3578** [551100kk/HSR-booking-system#3]
We are taking OOP 2019 Spring and would like to refer to your proposal. Could you please provide us the file?

**Comment by cyshih73** [comment]
Our team is humbled by your appreciation. Nevertheless, since we have all the source code in the repository, which file is missing and you would like to request?

**Comment by edenxu3578** [comment]
> Our team is humbled by your appreciation. Nevertheless, since we have all the source code in the repository, which file is missing and you would like to request?

We have some problems when write the draft of the optional project, but we cannot find the draft in the repository.

**Comment by edenxu3578** [comment]
> Our team is humbled by your appreciation. Nevertheless, since we have all the source code in the repository, which file is missing and you would like to request?

We have some problems when writing the draft of the optional project, but we cannot find the draft in the repository.

**Comment by cyshih73** [comment]
What should a draft look like? Would you mind explaining what is that mean?
Does it have anything to do with those UML diagrams?
@dalai8963 Please help look into the issue.

**Comment by woolninesun** [comment]
@shihehe73 
The draft of the optional project needs to write the "program architecture" part. We don't know how to write it, so we would like to refer to yours proposal outline about "program architecture".

**Comment by cyshih73** [comment]
May take a look at our [exquisite powerpoint](https://drive.google.com/file/d/1ONjnkWpKoLq4mDOP-TYx8_lMYXj1I4ON/view?usp=sharing).
Log in with your CSIE account to see whether this is what you needed. Thanks.
Don't forget to roll up your sleeves and be willing to work hard.
